apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: webhook-patch-sa
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: webhook-patch-secrets-role
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: webhook-patch-secrets-role-binding
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation
subjects:
- kind: ServiceAccount
  name: webhook-patch-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: webhook-patch-secrets-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-mutating-webhook-cluster-role
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-mutating-webhook-cluster-role-binding
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation
subjects:
- kind: ServiceAccount
  name: webhook-patch-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: patch-mutating-webhook-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-webhook-job
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: patch-webhook-pod
    spec:
      serviceAccountName: webhook-patch-sa
      containers:
      - name: patch-webhook-container
        image: {{ .Values.webhookCert.image.repository }}:{{ .Values.webhookCert.image.tag }}
        imagePullPolicy: {{ .Values.webhookCert.image.pullPolicy }}
        args:
        - patch
        - --webhook-name=pod-identity-webhook
        - --namespace={{ .Release.Namespace }}
        - --secret-name={{ .Values.webhookCert.config.secretName }}
        - --patch-validating=false
      restartPolicy: Never
