apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: irsa
  name: certgen-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: irsa
  name: certgen-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: irsa
roleRef:
  kind: Role
  name: certgen-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: certgen-job
  namespace: irsa
spec:
  template:
    metadata:
      name: certgen-pod
    spec:
      containers:
      - name: certgen-container
        image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.3.0
        args:
        - create
        - --host=pod-identity-webhook,pod-identity-webhook.irsa,pod-identity-webhook.irsa.svc,pod-identity-webhook.irsa.svc.local
        - --namespace=irsa
        - --secret-name=pod-identity-webhook-cert
        - --cert-name=tls.crt
        - --key-name=tls.key
      restartPolicy: Never
