apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-mutating-webhook-cluster-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-mutating-webhook-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: irsa
roleRef:
  kind: ClusterRole
  name: patch-mutating-webhook-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-webhook-job
  namespace: irsa
spec:
  template:
    metadata:
      name: patch-webhook-pod
    spec:
      serviceAccountName: default
      containers:
      - name: patch-webhook-container
        image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.3.0
        args:
        - patch
        - --webhook-name=pod-identity-webhook
        - --namespace=irsa
        - --secret-name=pod-identity-webhook-cert
        - --patch-validating=false
      restartPolicy: Never
